import "abla/compiler"

val target = #compilerDefineTarget(
    "esp32-riscv",
    "riscv32-esp-unknown-elf",
    "elf",
    "none",
    "none",
    false,
    false
)

val built = #compilerBuildProgram(
    "abla-embedded-charger-aw32001",
    "examples/charger-aw32001/main.ab",
    "build/examples/charger-aw32001/abla_app.o",
    "esp32-riscv",
    "object",
    false,
    false
)

fun main: int = if (target && built) 0 else 1
