import "abla/compiler"

val target = #compilerDefineTarget(
    "esp32s3-xtensa",
    "xtensa-esp-unknown-elf",
    "elf",
    "none",
    "none",
    false,
    false
)

val built = #compilerBuildProgram(
    "abla-embedded-board-detect-s3",
    "examples/board-detect-s3/main.ab",
    "build/examples/board-detect-s3/abla_app.o",
    "esp32s3-xtensa",
    "object",
    false,
    false
)

fun main: int = if (target && built) 0 else 1
