trusted noescape extern:"c" fun esp_sleep_enable_ext0_wakeup(
    pin: i32,
    level: i32
): i32
trusted noescape extern:"c" fun esp_sleep_get_wakeup_cause(): i32
trusted noescape extern:"c" fun esp_deep_sleep_start(): void

trusted fun wakeOnLow(pin: int): bool =
    esp_sleep_enable_ext0_wakeup(pin, 0) == 0

trusted fun wakeCause(): int {
    val result: int = esp_sleep_get_wakeup_cause()
    result
}

trusted fun deepSleep(): void {
    esp_deep_sleep_start()
    return
}
