import "./types.ab"

type Sh200q = int

trusted fun sh200q(bus: I2cBus): Sh200q = Sh200q(
    if (bus.valid()) bus.device(108, 400000) & 4294967295 else 0
)

fun Sh200q.valid(): bool = this != 0
fun Sh200q.device(): I2cDevice = I2cDevice(this & 4294967295)
fun Sh200q.accelerationScale(): f64 = 8.0 / 32768.0
fun Sh200q.gyroscopeScale(): f64 = 2000.0 / 32768.0
fun Sh200q.temperatureScale(): f64 = 1.0 / 333.87
fun Sh200q.temperatureOffset(): f64 = 21.0

trusted fun Sh200q.whoAmI(): int =
    if (this.valid()) this.device().readRegister8(48) else 0

trusted fun Sh200q.begin(): int {
    if (!this.valid() || this.whoAmI() != 24) return imuSpecNone
    val device = this.device()
    if (!device.updateRegister8(194, 4, 4)) return imuSpecNone
    imuDelay(1)
    if (!device.updateRegister8(194, 4, 0)) return imuSpecNone
    imuDelay(1)
    if (!device.updateRegister8(216, 128, 128)) return imuSpecNone
    imuDelay(1)
    if (!device.updateRegister8(216, 128, 0)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(120, 97)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(120, 0)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(14, 145)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(15, 19)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(17, 3)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(18, 0)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(20, 32)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(22, 1)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(43, 0)) return imuSpecNone
    imuDelay(1)
    if (!device.writeRegister8(186, 192)) return imuSpecNone
    imuDelay(1)
    if (!device.updateRegister8(202, 16, 16)) return imuSpecNone
    imuDelay(1)
    if (!device.updateRegister8(202, 16, 0)) return imuSpecNone
    imuSpecAcceleration | imuSpecGyroscope
}

trusted fun Sh200q.close(): bool =
    this.valid() && this.device().close()

trusted fun Sh200q.dataReady(): bool =
    this.valid() && (this.device().readRegister8(44) & 32) != 0

trusted fun Sh200q.readAccelerationRaw(): ImuAxes =
    if (this.valid()) this.device().readImuAxesLittleEndian(0)
    else invalidImuAxes()

trusted fun Sh200q.readGyroscopeRaw(): ImuAxes =
    if (this.valid()) this.device().readImuAxesLittleEndian(6)
    else invalidImuAxes()

trusted fun Sh200q.readTemperatureRaw(): ImuSample =
    if (this.valid()) this.device().readImuSampleLittleEndian(12)
    else invalidImuSample()
