import "../src/input/button.ab"

fun main: int {
    var state = buttonState(false, 0)
    state = state.update(true, 1)
    state = state.update(true, 12)
    val pressed = state.wasPressed() && state.isPressed()
    state = state.update(true, 520)
    val held = state.wasHold() && state.isHolding()
    state = state.update(false, 521)
    state = state.update(false, 532)
    val heldRelease = state.wasReleased() && !state.wasClicked()

    state = buttonState(false, 1000)
    state = state.update(true, 1001)
    state = state.update(true, 1012)
    state = state.update(false, 1013)
    state = state.update(false, 1024)
    val clicked = state.wasClicked() && state.getClickCount() == 1
    state = state.update(false, 1275)
    val single = state.wasSingleClicked()

    if (pressed && held && heldRelease && clicked && single) 42 else 1
}
