import "../src/m5stack.ab"

fun main: int {
    val board = m5AtomEcho()
    val audio = board.audio(16000)
    val source = board.boardId().buttonASource()
    if (board.buttonA() == Pin(39) && board.rgbLed() == RgbLed(27) &&
        board.portAClock() == Pin(32) && board.portAData() == Pin(26) &&
        audio.portNumber() == 0 && audio.pinsValue().clockPin() == 19 &&
        audio.pinsValue().wordSelectPin() == 33 &&
        audio.pinsValue().outputPin() == 22 &&
        audio.pinsValue().inputPin() == 23 &&
        source.pin().number() == 39 && source.activeLow()) 42 else 1
}
