import "../../src/esp32/wifi.ab"
import "../../src/esp32/serial.ab"
import "../../src/arduino/time.ab"

val station = wifiStation()
val log = serial()

@export("_Z5setupv")
trusted fun setup(): void {
    log.line("Wi-Fi connect from Abla")
    if (station.initialize() &&
        station.connect("YOUR_SSID", "YOUR_PASSWORD") &&
        station.waitForAddress(12000)) {
        log.line("Wi-Fi connected")
        station.sleep(true)
    } else log.line("Wi-Fi connection failed")
}

@export("_Z4loopv")
fun loop(): void = delay(1000)
