import "abla/compiler"

val target = #compilerDefineTarget(
    "esp32-xtensa",
    "xtensa-esp-unknown-elf",
    "elf",
    "none",
    "none",
    false,
    false
)

val built = #compilerBuildProgram(
    "abla-embedded-rtc-pcf8563",
    "examples/rtc-pcf8563/main.ab",
    "build/examples/rtc-pcf8563/abla_app.o",
    "esp32-xtensa",
    "object",
    false,
    false
)

fun main: int = if (target && built) 0 else 1
