import "../../src/m5stack/atom_echo.ab"
import "../../src/arduino/time.ab"
import "../../src/input/button.ab"
import "../../src/esp32/button.ab"

val board = m5AtomEcho()
var buttonA = board.buttonA().asButton()

@export("_Z5setupv")
trusted fun setup(): void = board.initialize()

@export("_Z4loopv")
trusted fun loop(): void {
    buttonA = buttonA.update()
    if (buttonA.isPressed()) board.rgbLed().set(0, 24, 0)
    else board.rgbLed().off()
    delay(10)
}
