import "../../src/m5stack/atom_echo.ab"
import "../../src/arduino/time.ab"
import "../../src/input/button.ab"

val board = m5AtomEcho()
var button = buttonState(false, 0)

@export("_Z5setupv")
trusted fun setup(): void = board.initialize()

@export("_Z4loopv")
trusted fun loop(): void {
    button = button.update(!board.buttonA().read(), millis())
    if (button.isPressed()) board.rgbLed().set(0, 24, 0)
    else board.rgbLed().off()
    delay(10)
}
