import "abla/compiler"

val target = #compilerDefineTarget(
    "esp32-xtensa",
    "xtensa-esp-unknown-elf",
    "elf",
    "none",
    "none",
    false,
    false
)

val built = #compilerBuildProgram(
    "abla-embedded-st7789-fill",
    "examples/st7789-fill/main.ab",
    "build/examples/st7789-fill/abla_app.o",
    "esp32-xtensa",
    "object",
    false,
    false
)

val benchmarkBuilt = #compilerBuildProgram(
    "abla-embedded-st7789-benchmark",
    "examples/st7789-fill/benchmark.ab",
    "build/examples/st7789-fill/abla_benchmark.o",
    "esp32-xtensa",
    "object",
    false,
    false
)

fun main: int = if (target && built && benchmarkBuilt) 0 else 1
